filebeat.inputs:
- type: filestream
  id: sms-logs
  enabled: true
  paths:
    - /usr/share/filebeat/sms_logs/*.log

output.logstash:
  hosts: ["logstash:5044"]

logging.level: debug
logging.to_stderr: true
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7