version: '3.8'

services:
  postgres:
    image: postgres
    container_name: sms_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./infrastructure/database/postgres_data:/var/lib/postgresql/data
