server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: localhost
  port: 5432
  name: sms_db
  user: dev_user
  password: dev_password
  ssl_mode: disable
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10

elasticsearch:
  host: localhost
  port: 9200
  username: ""
  password: ""
  index: server_logs

jwt:
  secret: your-very-secure-secret-key-here-at-least-32-chars-long
  expiry: 24h

smtp:
  host: smtp.gmail.com
  port: 587
  username: your-email@gmail.com
  password: your-app-password
  from: your-email@gmail.com
  admin_email: admin@example.com

log:
  level: debug
  file: sms_dev.log
  max_size: 1
  max_backups: 10
  max_age: 30
  compression: true

monitoring:
  interval: 60s

app:
  environment: development
  name: Server Management System
  version: 1.0.0