syntax = "proto3";

package user;

option go_package = ".;userpb";

service UserService {
  rpc GetUserByEmail(GetUserByEmailRequest) returns (GetUserByEmailResponse);
}

message GetUserByEmailRequest {
  string email = 1;
}

message GetUserByEmailResponse {
  User user = 1;
}

// User message definition
message User {
  string id = 1;
  string email = 2;
  string password = 3; // Hashed password
  repeated Scope scopes = 4;
}

// Scope message definition
message Scope {
  string id = 1;
  string name = 2;
}
