input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }

  mutate {
    rename => {
      "[LEVEL]" => "level"
      "[TIME]" => "timestamp"
      "[SERVICE]" => "service"
      "[LINE]" => "line"
      "[CALLER]" => "caller"
      "[MESSAGE]" => "message"
    }
  }

  date {
    match => ["timestamp", "ISO8601"]
    timezone => "UTC"
  }

  mutate {
    lowercase => ["level", "service"]
    gsub => ["service", " ", "_"]
  }

  if [service] {
    mutate {
      add_tag => ["service_%{service}", "level_%{level}"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logs-%{service}-%{+YYYY.MM.dd}"
    action => "create"
  }

  stdout { codec => rubydebug }
}